/**
 * ATUL-1 — Skills Data
 *
 * Every skill is represented as advanced technology with visual metaphors.
 * Java → Glowing energy crystal, Spring Boot → Green reactor core, etc.
 */

import type { Skill } from '@/types';

export const skills: Skill[] = [
  {
    id: 'java',
    name: 'Java',
    category: 'languages',
    proficiency: 90,
    icon: '☕',
    color: '#ED8B00',
    description: 'Core Java, OOP, Collections, Multithreading, Streams API, Design Patterns. The foundation of all systems.',
    relatedProjects: ['ems-01', 'lms-02', 'ecom-03'],
  },
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'frameworks',
    proficiency: 85,
    icon: '🍃',
    color: '#6DB33F',
    description: 'Spring Boot, Spring MVC, Spring Data JPA, Spring Security, REST APIs, Microservices architecture.',
    relatedProjects: ['ems-01', 'lms-02', 'ecom-03', 'acn-04'],
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'languages',
    proficiency: 75,
    icon: '📘',
    color: '#3178C6',
    description: 'Type-safe JavaScript development. Interfaces, generics, advanced types, and modern ES features.',
    relatedProjects: ['atul-1'],
  },
  {
    id: 'react',
    name: 'React',
    category: 'frameworks',
    proficiency: 70,
    icon: '⚛️',
    color: '#61DAFB',
    description: 'React 19, Hooks, Context API, Server Components, component architecture, and state management.',
    relatedProjects: ['atul-1'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'frameworks',
    proficiency: 70,
    icon: '▲',
    color: '#000000',
    description: 'Next.js 15, App Router, SSR, SSG, API routes, middleware, and full-stack React development.',
    relatedProjects: ['atul-1'],
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'databases',
    proficiency: 80,
    icon: '🗄️',
    color: '#4479A1',
    description: 'Relational database design, complex queries, indexing, normalization, and performance optimization.',
    relatedProjects: ['ems-01', 'lms-02', 'ecom-03'],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'databases',
    proficiency: 75,
    icon: '🐘',
    color: '#336791',
    description: 'Advanced PostgreSQL features, JSON queries, window functions, and database administration.',
    relatedProjects: ['ecom-03'],
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'databases',
    proficiency: 65,
    icon: '⚡',
    color: '#DC382D',
    description: 'In-memory caching, session management, pub/sub messaging, and distributed cache patterns.',
    relatedProjects: ['ecom-03'],
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'devops',
    proficiency: 70,
    icon: '🐳',
    color: '#2496ED',
    description: 'Containerization, Docker Compose, multi-stage builds, container networking, and volume management.',
    relatedProjects: ['acn-04'],
  },
  {
    id: 'git',
    name: 'Git',
    category: 'tools',
    proficiency: 85,
    icon: '🔀',
    color: '#F05032',
    description: 'Version control, branching strategies, code review workflows, CI/CD integration, and collaboration.',
    relatedProjects: ['ems-01', 'lms-02', 'ecom-03', 'acn-04', 'atul-1'],
  },
  {
    id: 'microservices',
    name: 'Microservices',
    category: 'architecture',
    proficiency: 65,
    icon: '🔗',
    color: '#8B5CF6',
    description: 'Distributed systems, service discovery, API gateways, inter-service communication, and event-driven architecture.',
    relatedProjects: ['acn-04'],
  },
  {
    id: 'aws',
    name: 'AWS',
    category: 'cloud',
    proficiency: 50,
    icon: '☁️',
    color: '#FF9900',
    description: 'EC2, S3, RDS, Lambda, IAM, and cloud infrastructure patterns. Currently expanding expertise.',
    relatedProjects: [],
  },
  {
    id: 'threejs',
    name: 'Three.js',
    category: 'frameworks',
    proficiency: 60,
    icon: '🎮',
    color: '#3B82F6',
    description: '3D graphics, WebGL, React Three Fiber, shaders, particle systems, and interactive 3D experiences.',
    relatedProjects: ['atul-1'],
  },
  {
    id: 'spring-security',
    name: 'Spring Security',
    category: 'frameworks',
    proficiency: 70,
    icon: '🔒',
    color: '#6DB33F',
    description: 'Authentication, authorization, JWT, OAuth2, role-based access control, and security best practices.',
    relatedProjects: ['ems-01', 'ecom-03'],
  },
];